from typing import List, Dict, Any
from pathlib import Path
from datetime import datetime
from .base import Exporter
from ..core.types import PacketData, ProtocolType
from ..common.exceptions import ExportError


class MarkdownExporter(Exporter):
    """Export analysis results to Markdown."""
    
    def export(self, packets: List[PacketData], output_path: Path, **kwargs) -> None:
        """Export packets to Markdown report."""
        try:
            content = self.export_string(packets, **kwargs)
            with open(output_path, 'w') as f:
                f.write(content)
        except Exception as e:
            raise ExportError(f"Failed to export Markdown: {e}")
    
    def export_string(self, packets: List[PacketData], **kwargs) -> str:
        """Export packets as Markdown string."""
        lines = []
        
        # Header
        lines.append("# TrafficLab Analysis Report")
        lines.append("")
        lines.append(f"**Generated:** {datetime.now().isoformat()}")
        lines.append(f"**Packets:** {len(packets)}")
        lines.append("")
        
        # Statistics
        lines.append("## Statistics")
        lines.append("")
        
        total_bytes = sum(p.length for p in packets)
        lines.append(f"- **Total Packets:** {len(packets)}")
        lines.append(f"- **Total Bytes:** {total_bytes:,}")
        lines.append(f"- **Average Packet Size:** {total_bytes / len(packets) if packets else 0:.2f} bytes")
        lines.append("")
        
        # Protocol distribution
        lines.append("## Protocol Distribution")
        lines.append("")
        lines.append("| Protocol | Count | Percentage |")
        lines.append("|----------|-------|------------|")
        
        proto_counts = {}
        for packet in packets:
            proto = packet.protocol.value
            proto_counts[proto] = proto_counts.get(proto, 0) + 1
        
        for proto, count in sorted(proto_counts.items(), key=lambda x: x[1], reverse=True):
            percentage = (count / len(packets)) * 100 if packets else 0
            lines.append(f"| {proto} | {count} | {percentage:.1f}% |")
        
        lines.append("")
        
        # Top talkers
        lines.append("## Top Talkers")
        lines.append("")
        lines.append("| Address | Bytes |")
        lines.append("|---------|-------|")
        
        talkers = {}
        for packet in packets:
            src = packet.source.ipv4 or packet.source.mac or "unknown"
            talkers[src] = talkers.get(src, 0) + packet.length
        
        for addr, bytes_count in sorted(talkers.items(), key=lambda x: x[1], reverse=True)[:10]:
            lines.append(f"| {addr} | {bytes_count:,} |")
        
        lines.append("")
        
        # Packet size histogram
        lines.append("## Packet Size Distribution")
        lines.append("")
        lines.append("| Size Range | Count |")
        lines.append("|------------|-------|")
        
        bins = [0, 64, 128, 256, 512, 1024, 1500, 9000]
        hist = {}
        for packet in packets:
            size = packet.length
            for bin_size in bins:
                if size <= bin_size:
                    hist[bin_size] = hist.get(bin_size, 0) + 1
                    break
            else:
                hist["9000+"] = hist.get("9000+", 0) + 1
        
        for size, count in sorted(hist.items()):
            lines.append(f"| <= {size} | {count} |")
        
        lines.append("")
        
        # Sample packets
        lines.append("## Sample Packets (First 10)")
        lines.append("")
        lines.append("| # | Timestamp | Source | Destination | Protocol | Length |")
        lines.append("|---|-----------|--------|-------------|----------|--------|")
        
        for i, packet in enumerate(packets[:10], 1):
            src = packet.source.ipv4 or packet.source.mac or "unknown"
            dst = packet.destination.ipv4 or packet.destination.mac or "unknown"
            lines.append(f"| {i} | {packet.timestamp.isoformat()} | {src} | {dst} | {packet.protocol.value} | {packet.length} |")
        
        lines.append("")
        lines.append("---")
        lines.append(f"*Report generated by TrafficLab v1.0.0*")
        
        return "\n".join(lines)
