from typing import List, Dict, Any
from pathlib import Path
from datetime import datetime
from ..core.types import PacketData
from ..exporters.markdown_exporter import MarkdownExporter


class ReportGenerator:
    """Generate comprehensive reports."""
    
    def __init__(self):
        self.markdown_exporter = MarkdownExporter()
    
    def generate_report(self, packets: List[PacketData], analysis: Dict[str, Any]) -> str:
        """Generate a comprehensive report."""
        lines = []
        
        # Header
        lines.append("# TrafficLab Analysis Report")
        lines.append("")
        lines.append(f"**Generated:** {datetime.now().isoformat()}")
        lines.append(f"**Packets:** {len(packets)}")
        lines.append("")
        
        # Summary
        if "summary" in analysis:
            lines.append("## Summary")
            lines.append("")
            summary = analysis["summary"]
            lines.append(f"- **Total Packets:** {summary.get('total_packets', 0):,}")
            lines.append(f"- **Total Bytes:** {summary.get('total_bytes', 0):,}")
            lines.append(f"- **Duration:** {summary.get('duration_seconds', 0):.2f} seconds")
            lines.append(f"- **Average Packet Size:** {summary.get('average_packet_size', 0):.2f} bytes")
            lines.append(f"- **Packets Per Second:** {summary.get('packets_per_second', 0):.2f}")
            lines.append(f"- **Bytes Per Second:** {summary.get('bytes_per_second', 0):.2f}")
            lines.append("")
        
        # Protocol distribution
        if "protocols" in analysis and "protocols" in analysis["protocols"]:
            lines.append("## Protocol Distribution")
            lines.append("")
            lines.append("| Protocol | Packets | Bytes | Packet % | Byte % |")
            lines.append("|----------|---------|-------|----------|--------|")
            
            for proto in analysis["protocols"]["protocols"]:
                lines.append(
                    f"| {proto['name']} | {proto['packets']:,} | {proto['bytes']:,} | "
                    f"{proto['packet_percentage']:.1f}% | {proto['byte_percentage']:.1f}% |"
                )
            lines.append("")
        
        # Top talkers
        if "top_talkers" in analysis:
            lines.append("## Top Talkers")
            lines.append("")
            lines.append("| Address | Bytes | Percentage |")
            lines.append("|---------|-------|------------|")
            
            for talker in analysis["top_talkers"][:10]:
                lines.append(f"| {talker['address']} | {talker['bytes']:,} | {talker.get('percentage', 0):.1f}% |")
            lines.append("")
        
        # Flows
        if "flows" in analysis and "flows" in analysis["flows"]:
            lines.append("## Top Flows")
            lines.append("")
            lines.append("| Source | Destination | Protocol | Packets | Bytes | Duration |")
            lines.append("|--------|-------------|----------|---------|-------|----------|")
            
            for flow in analysis["flows"]["flows"][:10]:
                src = f"{flow['source']['ipv4'] or flow['source']['mac']}:{flow['source']['port'] or ''}"
                dst = f"{flow['destination']['ipv4'] or flow['destination']['mac']}:{flow['destination']['port'] or ''}"
                lines.append(f"| {src} | {dst} | {flow['protocol']} | {flow['packets']} | {flow['bytes']:,} | {flow['duration']:.2f}s |")
            lines.append("")
        
        # Footer
        lines.append("---")
        lines.append(f"*Report generated by TrafficLab v1.0.0*")
        
        return "\n".join(lines)
    
    def save_report(self, packets: List[PacketData], analysis: Dict[str, Any], output_path: Path) -> None:
        """Save report to file."""
        report = self.generate_report(packets, analysis)
        with open(output_path, 'w') as f:
            f.write(report)
